### ISSUE TITLE
请问有Fine-tuning方面的说明吗

### ISSUE THREAD

**Issue by qiujz** [qhduan/CPM-LM-TF2#1]

**Comment by hurricanedjp** [comment]
finetune时需要多少GPU资源呢

**Comment by qhduan** [comment]
理论上是可以，不过模型在fp32的时候光模型文件就9GB了，用GPU+Adam之类优化器可能至少16GB显存文件了

我个人没这个资源（显卡&时间都没有），至少暂时应该不会做这方面的处理

如果只是从头训练一个GPT Small，以后我会给出一些文章、代码、说明

如果对于CPM模型有想法，建议研究下原REPO和原REPO中提到的Nvidia的REPO，应该还是能自己研究出来的，估计大概至少需要两张8GB显存的显卡

详细的具体怎么做，建议自己研究，或者等智源研究院的后续动作

**Comment by sssdjj** [comment]
给个模型下载链接吧

**Comment by qhduan** [comment]
> 给个模型下载链接吧

看README
