### ISSUE TITLE
生成文本太慢

### ISSUE THREAD

**Issue by Biaocsu** [qhduan/CPM-LM-TF2#11]
你好，该项目生成文本实在有点慢，平均2.6s一条数据，使用的是GPU机器，请问有什么方法可以加速吗？

**Comment by qhduan** [comment]
GPU可以尝试不同的推力器

或者转换到onnx，然后可以尝试用 https://github.com/triton-inference-server/server 据说效果不错

不过这些代码相对就要改的可能就比较多了，我能提供的帮助比较少

**Comment by Biaocsu** [comment]
多谢哈

**Comment by qhduan** [comment]
发现自己，推理器打错字了。

毕竟开源而已，售后无法完全保证～～不客气

**Comment by Biaocsu** [comment]
哈哈哈哈哈哈

**Comment by Biaocsu** [comment]
您好，我决定还是换个模型来考察。您有效果不错、推理也快的　小说文本生成模型推荐吗？多谢

**Comment by qhduan** [comment]
> 您好，我决定还是换个模型来考察。您有效果不错、推理也快的　小说文本生成模型推荐吗？多谢

不知道呢，我自己没有试过很多
