### ISSUE TITLE
如何计算perplexity（困惑度）

### ISSUE THREAD

**Issue by FannierPeng** [qhduan/CPM-LM-TF2#4]
请问在这个项目下如何计算perplexity（困惑度）？我有一点疑惑是在于，保存的tensorflow_hub模型似乎是专为文本生成定制的(在tf2gpt/loading.ipynb中看到的相关代码)。我想使用你给出的模型参数，但是做一个前向传播，我所需要用到的是['output0']之前的一层（未经argmax），然后与label做一下交叉熵损失计算，从而算出perplexity。请问你有什么建议吗？感谢！
   
您代码中是这样做文本生成的:
 ret = gpt.signatures['serving_default'](
        inp=inputs,
        length=length,
        top_p=tf.constant(top_p, tf.float32),
        temperature=tf.constant(temperature, tf.float32)
    )['output_0']

**Comment by FannierPeng** [comment]
@qhduan

**Comment by qhduan** [comment]
你看 

https://github.com/qhduan/CPM-LM-TF2/blob/main/load_pytorch_v2.ipynb

文件的 In [7]

print(gpt(tf.constant([[1]])).shape)  
(1, 1, 30000)

这实际上已经是输出logits的了，词表是3万个，你可以只保留到这部分的输出就好了

**Comment by FannierPeng** [comment]
按issue上的https://github.com/qhduan/CPM-LM-TF2/issues/5#issuecomment-733634204
重新保存了模型，但是输入tensor的shape还是会固定为(None, 1)，输入其他shape会报错。

图1：重新保存模型，模型输入格式为None？这点有疑问。
![image](https://user-images.githubusercontent.com/40656312/100411949-26e64500-30ae-11eb-8a3b-2ee2bfdbd523.png)

图2：重新load新保存的模型，试验一下不同的输入，是否能得到输出。输入为tf.constant([[1],[2],[3]])).shape， 即tensor shape=(3，1) ，可以得到输出（3，1，30000）。
![image](https://user-images.githubusercontent.com/40656312/100412315-43cf4800-30af-11eb-8020-aecc30a37403.png)

输入为tf.constant([[1,2,3]]，即tensor shape=(1，3) ，会报错。
![image](https://user-images.githubusercontent.com/40656312/100412362-6cefd880-30af-11eb-8f41-b8387bf34b08.png)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-262-c6601cf07edf> in <module>
----> 1 print(model(tf.constant([[1,2,3]])).shape)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    983 
    984         with ops.enable_auto_cast_variables(self._compute_dtype_object):
--> 985           outputs = call_fn(inputs, *args, **kwargs)
    986 
    987         if self._activity_regularizer:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py in return_outputs_and_add_losses(*args, **kwargs)
     69     inputs = args[inputs_arg_index]
     70     args = args[inputs_arg_index + 1:]
---> 71     outputs, losses = fn(inputs, *args, **kwargs)
     72     layer.add_loss(losses, inputs=inputs)
     73 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py in wrap_with_training_arg(*args, **kwargs)
    168         training,
    169         lambda: replace_training_and_call(True),
--> 170         lambda: replace_training_and_call(False))
    171 
    172   # Create arg spec for decorated function. If 'training' is not defined in the

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/tf_utils.py in smart_cond(pred, true_fn, false_fn, name)
     63         pred, true_fn=true_fn, false_fn=false_fn, name=name)
     64   return smart_module.smart_cond(
---> 65       pred, true_fn=true_fn, false_fn=false_fn, name=name)
     66 
     67 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/smart_cond.py in smart_cond(pred, true_fn, false_fn, name)
     54       return true_fn()
     55     else:
---> 56       return false_fn()
     57   else:
     58     return control_flow_ops.cond(pred, true_fn=true_fn, false_fn=false_fn,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py in <lambda>()
    168         training,
    169         lambda: replace_training_and_call(True),
--> 170         lambda: replace_training_and_call(False))
    171 
    172   # Create arg spec for decorated function. If 'training' is not defined in the

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py in replace_training_and_call(training)
    163     def replace_training_and_call(training):
    164       set_training_arg(training, training_arg_index, args, kwargs)
--> 165       return wrapped_call(*args, **kwargs)
    166 
    167     return tf_utils.smart_cond(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    812       # In this case we have not created variables on the first call. So we can
    813       # run the first trace but we should fail if variables are created.
--> 814       results = self._stateful_fn(*args, **kwds)
    815       if self._created_variables:
    816         raise ValueError("Creating variables on a non-first call to a function"

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2826     """Calls a graph function specialized to the inputs."""
   2827     with self._lock:
-> 2828       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
   2829     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2830 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3211 
   3212       self._function_cache.missed.add(call_context_key)
-> 3213       graph_function = self._create_graph_function(args, kwargs)
   3214       self._function_cache.primary[cache_key] = graph_function
   3215       return graph_function, args, kwargs

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3073             arg_names=arg_names,
   3074             override_flat_arg_shapes=override_flat_arg_shapes,
-> 3075             capture_by_value=self._capture_by_value),
   3076         self._function_attributes,
   3077         function_spec=self.function_spec,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    984         _, original_func = tf_decorator.unwrap(python_func)
    985 
--> 986       func_outputs = python_func(*func_args, **func_kwargs)
    987 
    988       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    598         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    599         # the function a weak reference to itself to avoid a reference cycle.
--> 600         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    601     weak_wrapped_fn = weakref.ref(wrapped_fn)
    602 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/function_deserialization.py in restored_function_body(*args, **kwargs)
    255         .format(_pretty_format_positional(args), kwargs,
    256                 len(saved_function.concrete_functions),
--> 257                 "\n\n".join(signature_descriptions)))
    258 
    259   concrete_function_objects = []

ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (3 total):
    * Tensor("x:0", shape=(1, 3), dtype=int32)
    * None
    * False
  Keyword arguments: {'training': False}

Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (3 total):
    * TensorSpec(shape=(None, 1), dtype=tf.int32, name='x')
    * None
    * False
  Keyword arguments: {'training': True}

Option 2:
  Positional arguments (3 total):
    * TensorSpec(shape=(None, 1), dtype=tf.int32, name='input_1')
    * None
    * False
  Keyword arguments: {'training': True}

Option 3:
  Positional arguments (3 total):
    * TensorSpec(shape=(None, 1), dtype=tf.int32, name='input_1')
    * None
    * False
  Keyword arguments: {'training': False}

Option 4:
  Positional arguments (3 total):
    * TensorSpec(shape=(None, 1), dtype=tf.int32, name='x')
    * None
    * False
  Keyword arguments: {'training': False}

**Comment by qhduan** [comment]
这个是有顺序要求的，避免误解，我还是写个例子看

https://github.com/qhduan/CPM-LM-TF2/blob/main/load_pytorch_v2_logits.ipynb

https://github.com/qhduan/CPM-LM-TF2/blob/main/test_logits.ipynb

**Comment by qhduan** [comment]
应该算完结了吧，如果有其他问题请开新的issue
