### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by PythonCyan** [qhduan/CPM-LM-TF2#7]
你好，当我在使用模型的时候（prediction_v2文件），按照给的例子，输入
`ret = sample(tokenizer, gpt, '''匆匆瞥了金威南一眼，深邃的眼眸有一层让人沉溺的雾气，她敛眸，跟他错开。''', 3, 3000, top_p=0.9, temperature=0.9)
for x in ret:
    print(x)
    print('-' * 20)
`
运行后，系统提示报错：
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [1,1,0,0] vs. [3,32,0,1024]
	 [[{{node StatefulPartitionedCall/while/body/_1043/while/StatefulPartitionedCall/gpt/layer00/attention/mul_2}}]] [Op:__inference_signature_wrapper_100226]

Function call stack:
signature_wrapper
可以问下，是什么导致的不~~

**Comment by qhduan** [comment]
请检查下tf版本，或者直接尝试下最新版

**Comment by PythonCyan** [comment]
好的，谢谢，我检查了下tf版本，目前是最新版本了，2.3.1，用你例子默认中的参数是不会报错的，但是我把生成句子的输出最大长度大于1000以后就开始报错了。不知道为什么。

**Comment by qhduan** [comment]
gpt/transformer的原理上有position embedding存在，这个模型最多1024，句子太长可能会超过，不一定严格的1024，可能更少也会报错

**Comment by qhduan** [comment]
如果暂时没问题我先关了，如果有其他问题欢迎开其他issue
