### ISSUE TITLE
请问如何实现由键盘循环输入测试内容？

### ISSUE THREAD

**Issue by NLPIG** [qhduan/CPM-LM-TF2#8]
作者你好，非常感谢您这一版本，让我们单卡/无卡也能进行测试并从中寻找灵感。
有一点遗憾，每次换内容的时候，需要重新运行（修改sample里面的内容），等待漫长的加载时间。
我参考了“GPT2-ML”这一项目的demo.py，利用input() 实现由键盘获取新的测试内容（无需重新运行py），可惜一直失败。
希望能得到您的指点！
谢谢！

**Comment by qhduan** [comment]
这个问题实在是和本repo无关，和python基础关系太大，建议在其他地方寻找答案
