### ISSUE TITLE
如何训练他的model

### ISSUE THREAD

**Issue by RyzeLLC** [qhduan/CPM-LM-TF2#9]
感谢您的付出，让我们用tensorflow-cpu也能运行
但是，如果我想对目前与训练模型做一些针对性训练，应该怎么去做呢？
hub.load()加载出模型gpt之后，怎样去做一些训练？
希望得到您的解答 
谢谢

**Comment by qhduan** [comment]
训练比较复杂，我暂时也没有资源和时间去训练，抱歉，建议自己参考其他gpt的repo研究

**Comment by RyzeLLC** [comment]
您好，感谢您百忙时间回复。但我有一个小问题想问一下：
文本生成模型 训练的是什么？是词性之间的联系或者什么之间的联系么？
喂养的语库越大越好么？
希望得到您的解答，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qhduan/CPM-LM-TF2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月22日(星期四) 凌晨0:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qhduan/CPM-LM-TF2] 如何训练他的model (#9)





 
训练比较复杂，我暂时也没有资源和时间去训练，抱歉，建议自己参考其他gpt的repo研究

**Comment by qhduan** [comment]
首先你这个问题已经超出了这个REPO的范畴

这个问题可能既很难回答，我也不觉得我能回答的很好

建议通过阅读文本生产模型相关的论文自己寻找答案

**Comment by RyzeLLC** [comment]
谢谢您的回复。
通过这两天查文献，我想我初步的了解了gpt-2的工作机制。
谢谢您对我的帮助和在git上的贡献。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qhduan/CPM-LM-TF2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 凌晨3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qhduan/CPM-LM-TF2] 如何训练他的model (#9)





 
首先你这个问题已经超出了这个REPO的范畴
 
这个问题可能既很难回答，我也不觉得我能回答的很好
 
建议通过阅读文本生产模型相关的论文自己寻找答案
